books = [
    {
        "author": "Miguel de Cervantes",
        "title": "Don Quixote",
        "rank": 1,
        "data": {
            "year": 1605,
            "genre": ["Novel", "Satire"],
            "original_language": "Spanish",
        },
    },
    {
        "author": "Leo Tolstoy",
        "title": "War and Peace",
        "rank": 2,
        "data": {
            "year": 1869,
            "genre": ["Historical Fiction", "War"],
            "original_language": "Russian",
        },
    },
    {
        "author": "George Orwell",
        "title": "1984",
        "rank": 3,
        "data": {
            "year": 1949,
            "genre": ["Dystopian", "Political Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Homer",
        "title": "The Odyssey",
        "rank": 4,
        "data": {
            "year": -800,
            "genre": ["Epic Poetry", "Adventure"],
            "original_language": "Ancient Greek",
        },
    },
    {
        "author": "Jane Austen",
        "title": "Pride and Prejudice",
        "rank": 5,
        "data": {
            "year": 1813,
            "genre": ["Romance", "Satire"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "Crime and Punishment",
        "rank": 6,
        "data": {
            "year": 1866,
            "genre": ["Philosophical Fiction", "Psychological Novel"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Herman Melville",
        "title": "Moby-Dick",
        "rank": 7,
        "data": {
            "year": 1851,
            "genre": ["Adventure", "Epic"],
            "original_language": "English",
        },
    },
    {
        "author": "Gabriel García Márquez",
        "title": "One Hundred Years of Solitude",
        "rank": 8,
        "data": {
            "year": 1967,
            "genre": ["Magic Realism", "Epic"],
            "original_language": "Spanish",
        },
    },
    {
        "author": "James Joyce",
        "title": "Ulysses",
        "rank": 9,
        "data": {
            "year": 1922,
            "genre": ["Modernist Novel", "Stream of Consciousness"],
            "original_language": "English",
        },
    },
    {
        "author": "Leo Tolstoy",
        "title": "Anna Karenina",
        "rank": 10,
        "data": {
            "year": 1877,
            "genre": ["Realist Novel", "Tragedy"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Mark Twain",
        "title": "Adventures of Huckleberry Finn",
        "rank": 11,
        "data": {
            "year": 1884,
            "genre": ["Adventure", "Satire"],
            "original_language": "English",
        },
    },
    {
        "author": "F. Scott Fitzgerald",
        "title": "The Great Gatsby",
        "rank": 12,
        "data": {
            "year": 1925,
            "genre": ["Tragedy", "Social Commentary"],
            "original_language": "English",
        },
    },
    {
        "author": "Marcel Proust",
        "title": "In Search of Lost Time",
        "rank": 13,
        "data": {
            "year": 1913,
            "genre": ["Modernist", "Philosophical"],
            "original_language": "French",
        },
    },
    {
        "author": "J.R.R. Tolkien",
        "title": "The Lord of the Rings",
        "rank": 14,
        "data": {
            "year": 1954,
            "genre": ["Fantasy", "Adventure"],
            "original_language": "English",
        },
    },
    {
        "author": "William Shakespeare",
        "title": "Hamlet",
        "rank": 15,
        "data": {
            "year": 1603,
            "genre": ["Tragedy", "Drama"],
            "original_language": "English",
        },
    },
    {
        "author": "Dante Alighieri",
        "title": "The Divine Comedy",
        "rank": 16,
        "data": {
            "year": 1320,
            "genre": ["Epic Poetry", "Religious"],
            "original_language": "Italian",
        },
    },
    {
        "author": "Homer",
        "title": "The Iliad",
        "rank": 17,
        "data": {
            "year": -750,
            "genre": ["Epic Poetry", "War"],
            "original_language": "Ancient Greek",
        },
    },
    {
        "author": "Franz Kafka",
        "title": "The Metamorphosis",
        "rank": 18,
        "data": {
            "year": 1915,
            "genre": ["Absurdist Fiction", "Surrealism"],
            "original_language": "German",
        },
    },
    {
        "author": "Charles Dickens",
        "title": "Great Expectations",
        "rank": 19,
        "data": {
            "year": 1861,
            "genre": ["Bildungsroman", "Social Critique"],
            "original_language": "English",
        },
    },
    {
        "author": "Mary Shelley",
        "title": "Frankenstein",
        "rank": 20,
        "data": {
            "year": 1818,
            "genre": ["Gothic", "Science Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Albert Camus",
        "title": "The Stranger",
        "rank": 21,
        "data": {
            "year": 1942,
            "genre": ["Philosophical Fiction", "Existentialism"],
            "original_language": "French",
        },
    },
    {
        "author": "J.D. Salinger",
        "title": "The Catcher in the Rye",
        "rank": 22,
        "data": {
            "year": 1951,
            "genre": ["Coming-of-Age", "Realism"],
            "original_language": "English",
        },
    },
    {
        "author": "Joseph Heller",
        "title": "Catch-22",
        "rank": 23,
        "data": {
            "year": 1961,
            "genre": ["Satire", "War"],
            "original_language": "English",
        },
    },
    {
        "author": "George Orwell",
        "title": "Animal Farm",
        "rank": 24,
        "data": {
            "year": 1945,
            "genre": ["Political Satire", "Allegory"],
            "original_language": "English",
        },
    },
    {
        "author": "Harper Lee",
        "title": "To Kill a Mockingbird",
        "rank": 25,
        "data": {
            "year": 1960,
            "genre": ["Southern Gothic", "Bildungsroman"],
            "original_language": "English",
        },
    },
    {
        "author": "Emily Brontë",
        "title": "Wuthering Heights",
        "rank": 26,
        "data": {
            "year": 1847,
            "genre": ["Gothic", "Tragedy"],
            "original_language": "English",
        },
    },
    {
        "author": "Virginia Woolf",
        "title": "Mrs Dalloway",
        "rank": 27,
        "data": {
            "year": 1925,
            "genre": ["Modernist", "Stream of Consciousness"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "The Brothers Karamazov",
        "rank": 28,
        "data": {
            "year": 1880,
            "genre": ["Philosophical Fiction", "Mystery"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Ernest Hemingway",
        "title": "The Old Man and the Sea",
        "rank": 29,
        "data": {
            "year": 1952,
            "genre": ["Literary Fiction", "Adventure"],
            "original_language": "English",
        },
    },
    {
        "author": "Aldous Huxley",
        "title": "Brave New World",
        "rank": 30,
        "data": {
            "year": 1932,
            "genre": ["Dystopian", "Science Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "H.G. Wells",
        "title": "The War of the Worlds",
        "rank": 31,
        "data": {
            "year": 1898,
            "genre": ["Science Fiction", "Alien Invasion"],
            "original_language": "English",
        },
    },
    {
        "author": "Thomas Mann",
        "title": "The Magic Mountain",
        "rank": 32,
        "data": {
            "year": 1924,
            "genre": ["Philosophical Fiction", "Modernist"],
            "original_language": "German",
        },
    },
    {
        "author": "Charlotte Brontë",
        "title": "Jane Eyre",
        "rank": 33,
        "data": {
            "year": 1847,
            "genre": ["Romance", "Gothic"],
            "original_language": "English",
        },
    },
    {
        "author": "Jonathan Swift",
        "title": "Gulliver's Travels",
        "rank": 34,
        "data": {
            "year": 1726,
            "genre": ["Satire", "Adventure"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "The Idiot",
        "rank": 35,
        "data": {
            "year": 1869,
            "genre": ["Philosophical Fiction", "Psychological Novel"],
            "original_language": "Russian",
        },
    },
    {
        "author": "William Golding",
        "title": "Lord of the Flies",
        "rank": 36,
        "data": {
            "year": 1954,
            "genre": ["Allegory", "Adventure"],
            "original_language": "English",
        },
    },
    {
        "author": "Arthur Conan Doyle",
        "title": "Sherlock Holmes: The Complete Novels and Stories",
        "rank": 37,
        "data": {
            "year": 1887,
            "genre": ["Mystery", "Detective Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "John Steinbeck",
        "title": "The Grapes of Wrath",
        "rank": 38,
        "data": {
            "year": 1939,
            "genre": ["Historical Fiction", "Social Commentary"],
            "original_language": "English",
        },
    },
    {
        "author": "Franz Kafka",
        "title": "The Trial",
        "rank": 39,
        "data": {
            "year": 1925,
            "genre": ["Absurdist Fiction", "Surrealism"],
            "original_language": "German",
        },
    },
    {
        "author": "Gustave Flaubert",
        "title": "Madame Bovary",
        "rank": 40,
        "data": {
            "year": 1856,
            "genre": ["Realist Novel", "Tragedy"],
            "original_language": "French",
        },
    },
    {
        "author": "Hermann Hesse",
        "title": "Siddhartha",
        "rank": 41,
        "data": {
            "year": 1922,
            "genre": ["Philosophical Fiction", "Spirituality"],
            "original_language": "German",
        },
    },
    {
        "author": "Jules Verne",
        "title": "Twenty Thousand Leagues Under the Sea",
        "rank": 42,
        "data": {
            "year": 1870,
            "genre": ["Science Fiction", "Adventure"],
            "original_language": "French",
        },
    },
    {
        "author": "Margaret Mitchell",
        "title": "Gone with the Wind",
        "rank": 43,
        "data": {
            "year": 1936,
            "genre": ["Historical Fiction", "Romance"],
            "original_language": "English",
        },
    },
    {
        "author": "Joseph Conrad",
        "title": "Heart of Darkness",
        "rank": 44,
        "data": {
            "year": 1899,
            "genre": ["Novella", "Psychological Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Antoine de Saint-Exupéry",
        "title": "The Little Prince",
        "rank": 45,
        "data": {
            "year": 1943,
            "genre": ["Children's Literature", "Philosophical Fiction"],
            "original_language": "French",
        },
    },
    {
        "author": "Oscar Wilde",
        "title": "The Picture of Dorian Gray",
        "rank": 46,
        "data": {
            "year": 1890,
            "genre": ["Philosophical Fiction", "Gothic"],
            "original_language": "English",
        },
    },
    {
        "author": "Herman Melville",
        "title": "Billy Budd, Sailor",
        "rank": 47,
        "data": {
            "year": 1924,
            "genre": ["Novella", "Sea Story"],
            "original_language": "English",
        },
    },
    {
        "author": "Sun Tzu",
        "title": "The Art of War",
        "rank": 48,
        "data": {
            "year": "5th Century BC",
            "genre": ["Military Strategy", "Philosophy"],
            "original_language": "Chinese",
        },
    },
    {
        "author": "Kurt Vonnegut",
        "title": "Slaughterhouse-Five",
        "rank": 49,
        "data": {
            "year": 1969,
            "genre": ["Science Fiction", "Anti-War"],
            "original_language": "English",
        },
    },
    {
        "author": "Bram Stoker",
        "title": "Dracula",
        "rank": 50,
        "data": {
            "year": 1897,
            "genre": ["Gothic Horror", "Epistolary"],
            "original_language": "English",
        },
    },
    {
        "author": "Victor Hugo",
        "title": "Les Misérables",
        "rank": 51,
        "data": {
            "year": 1862,
            "genre": ["Historical Fiction", "Drama"],
            "original_language": "French",
        },
    },
    {
        "author": "George Eliot",
        "title": "Middlemarch",
        "rank": 52,
        "data": {
            "year": 1871,
            "genre": ["Realist Novel", "Social Critique"],
            "original_language": "English",
        },
    },
    {
        "author": "Alexandre Dumas",
        "title": "The Count of Monte Cristo",
        "rank": 53,
        "data": {
            "year": 1844,
            "genre": ["Adventure", "Historical Fiction"],
            "original_language": "French",
        },
    },
    {
        "author": "Mikhail Bulgakov",
        "title": "The Master and Margarita",
        "rank": 54,
        "data": {
            "year": 1967,
            "genre": ["Magic Realism", "Satire"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Thomas Mann",
        "title": "Buddenbrooks",
        "rank": 55,
        "data": {
            "year": 1901,
            "genre": ["Family Saga", "Realism"],
            "original_language": "German",
        },
    },
    {
        "author": "Toni Morrison",
        "title": "Beloved",
        "rank": 56,
        "data": {
            "year": 1987,
            "genre": ["Historical Fiction", "Magic Realism"],
            "original_language": "English",
        },
    },
    {
        "author": "E.M. Forster",
        "title": "A Passage to India",
        "rank": 57,
        "data": {
            "year": 1924,
            "genre": ["Historical Fiction", "Social Critique"],
            "original_language": "English",
        },
    },
    {
        "author": "Franz Kafka",
        "title": "The Castle",
        "rank": 58,
        "data": {
            "year": 1926,
            "genre": ["Absurdist Fiction", "Surrealism"],
            "original_language": "German",
        },
    },
    {
        "author": "Salman Rushdie",
        "title": "Midnight's Children",
        "rank": 59,
        "data": {
            "year": 1981,
            "genre": ["Magic Realism", "Historical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Jorge Luis Borges",
        "title": "Ficciones",
        "rank": 60,
        "data": {
            "year": 1944,
            "genre": ["Short Stories", "Magic Realism"],
            "original_language": "Spanish",
        },
    },
    {
        "author": "Ken Kesey",
        "title": "One Flew Over the Cuckoo's Nest",
        "rank": 61,
        "data": {
            "year": 1962,
            "genre": ["Psychological Fiction", "Social Commentary"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "Notes from Underground",
        "rank": 62,
        "data": {
            "year": 1864,
            "genre": ["Philosophical Fiction", "Psychological"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Hermann Hesse",
        "title": "Steppenwolf",
        "rank": 63,
        "data": {
            "year": 1927,
            "genre": ["Philosophical Fiction", "Existentialism"],
            "original_language": "German",
        },
    },
    {
        "author": "William Faulkner",
        "title": "As I Lay Dying",
        "rank": 64,
        "data": {
            "year": 1930,
            "genre": ["Modernist Novel", "Southern Gothic"],
            "original_language": "English",
        },
    },
    {
        "author": "Ernest Hemingway",
        "title": "A Farewell to Arms",
        "rank": 65,
        "data": {
            "year": 1929,
            "genre": ["War Novel", "Romance"],
            "original_language": "English",
        },
    },
    {
        "author": "Miguel de Unamuno",
        "title": "Mist",
        "rank": 66,
        "data": {
            "year": 1914,
            "genre": ["Existentialist Novel", "Metafiction"],
            "original_language": "Spanish",
        },
    },
    {
        "author": "Chinua Achebe",
        "title": "Things Fall Apart",
        "rank": 67,
        "data": {
            "year": 1958,
            "genre": ["Historical Fiction", "Tragedy"],
            "original_language": "English",
        },
    },
    {
        "author": "Milan Kundera",
        "title": "The Unbearable Lightness of Being",
        "rank": 68,
        "data": {
            "year": 1984,
            "genre": ["Philosophical Fiction", "Romance"],
            "original_language": "Czech",
        },
    },
    {
        "author": "Kazuo Ishiguro",
        "title": "The Remains of the Day",
        "rank": 69,
        "data": {
            "year": 1989,
            "genre": ["Historical Fiction", "Drama"],
            "original_language": "English",
        },
    },
    {
        "author": "Ray Bradbury",
        "title": "Fahrenheit 451",
        "rank": 70,
        "data": {
            "year": 1953,
            "genre": ["Dystopian", "Science Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "J.R.R. Tolkien",
        "title": "The Hobbit",
        "rank": 71,
        "data": {
            "year": 1937,
            "genre": ["Fantasy", "Adventure"],
            "original_language": "English",
        },
    },
    {
        "author": "Vladimir Nabokov",
        "title": "Lolita",
        "rank": 72,
        "data": {
            "year": 1955,
            "genre": ["Psychological Fiction", "Drama"],
            "original_language": "English",
        },
    },
    {
        "author": "Arthur Miller",
        "title": "Death of a Salesman",
        "rank": 73,
        "data": {
            "year": 1949,
            "genre": ["Drama", "Tragedy"],
            "original_language": "English",
        },
    },
    {
        "author": "William Shakespeare",
        "title": "Macbeth",
        "rank": 74,
        "data": {
            "year": 1606,
            "genre": ["Tragedy", "Drama"],
            "original_language": "English",
        },
    },
    {
        "author": "Lewis Carroll",
        "title": "Alice's Adventures in Wonderland",
        "rank": 75,
        "data": {
            "year": 1865,
            "genre": ["Children's Literature", "Fantasy"],
            "original_language": "English",
        },
    },
    {
        "author": "Daniel Defoe",
        "title": "Robinson Crusoe",
        "rank": 76,
        "data": {
            "year": 1719,
            "genre": ["Adventure", "Historical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "John Steinbeck",
        "title": "Of Mice and Men",
        "rank": 77,
        "data": {
            "year": 1937,
            "genre": ["Tragedy", "Social Commentary"],
            "original_language": "English",
        },
    },
    {
        "author": "Nathaniel Hawthorne",
        "title": "The Scarlet Letter",
        "rank": 78,
        "data": {
            "year": 1850,
            "genre": ["Historical Fiction", "Romance"],
            "original_language": "English",
        },
    },
    {
        "author": "Zora Neale Hurston",
        "title": "Their Eyes Were Watching God",
        "rank": 79,
        "data": {
            "year": 1937,
            "genre": ["Historical Fiction", "Romance"],
            "original_language": "English",
        },
    },
    {
        "author": "Ernest Hemingway",
        "title": "For Whom the Bell Tolls",
        "rank": 80,
        "data": {
            "year": 1940,
            "genre": ["War Novel", "Historical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "James Joyce",
        "title": "A Portrait of the Artist as a Young Man",
        "rank": 81,
        "data": {
            "year": 1916,
            "genre": ["Bildungsroman", "Modernist"],
            "original_language": "English",
        },
    },
    {
        "author": "Sylvia Plath",
        "title": "The Bell Jar",
        "rank": 82,
        "data": {
            "year": 1963,
            "genre": ["Semi-Autobiographical", "Psychological Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "John Milton",
        "title": "Paradise Lost",
        "rank": 83,
        "data": {
            "year": 1667,
            "genre": ["Epic Poetry", "Religious"],
            "original_language": "English",
        },
    },
    {
        "author": "Arthur C. Clarke",
        "title": "2001: A Space Odyssey",
        "rank": 84,
        "data": {
            "year": 1968,
            "genre": ["Science Fiction", "Space Exploration"],
            "original_language": "English",
        },
    },
    {
        "author": "Robert Louis Stevenson",
        "title": "Treasure Island",
        "rank": 85,
        "data": {
            "year": 1883,
            "genre": ["Adventure", "Children's Literature"],
            "original_language": "English",
        },
    },
    {
        "author": "Anne Frank",
        "title": "The Diary of a Young Girl",
        "rank": 86,
        "data": {
            "year": 1947,
            "genre": ["Autobiography", "War"],
            "original_language": "Dutch",
        },
    },
    {
        "author": "Isaac Asimov",
        "title": "Foundation",
        "rank": 87,
        "data": {
            "year": 1951,
            "genre": ["Science Fiction", "Epic"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "The Gambler",
        "rank": 88,
        "data": {
            "year": 1867,
            "genre": ["Psychological Fiction", "Drama"],
            "original_language": "Russian",
        },
    },
    {
        "author": "Paulo Coelho",
        "title": "The Alchemist",
        "rank": 89,
        "data": {
            "year": 1988,
            "genre": ["Adventure", "Quest"],
            "original_language": "Portuguese",
        },
    },
    {
        "author": "Yann Martel",
        "title": "Life of Pi",
        "rank": 90,
        "data": {
            "year": 2001,
            "genre": ["Adventure", "Philosophical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "William Faulkner",
        "title": "Light in August",
        "rank": 91,
        "data": {
            "year": 1932,
            "genre": ["Southern Gothic", "Modernist"],
            "original_language": "English",
        },
    },
    {
        "author": "Robert Louis Stevenson",
        "title": "The Strange Case of Dr Jekyll and Mr Hyde",
        "rank": 92,
        "data": {
            "year": 1886,
            "genre": ["Gothic Fiction", "Horror"],
            "original_language": "English",
        },
    },
    {
        "author": "Herman Melville",
        "title": "Bartleby, the Scrivener",
        "rank": 93,
        "data": {
            "year": 1853,
            "genre": ["Short Story", "Philosophical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Thomas Hardy",
        "title": "Jude the Obscure",
        "rank": 94,
        "data": {
            "year": 1895,
            "genre": ["Tragedy", "Social Critique"],
            "original_language": "English",
        },
    },
    {
        "author": "Umberto Eco",
        "title": "The Name of the Rose",
        "rank": 95,
        "data": {
            "year": 1980,
            "genre": ["Historical Mystery", "Philosophical Fiction"],
            "original_language": "Italian",
        },
    },
    {
        "author": "Victor Hugo",
        "title": "The Hunchback of Notre-Dame",
        "rank": 96,
        "data": {
            "year": 1831,
            "genre": ["Romance", "Gothic Fiction"],
            "original_language": "French",
        },
    },
    {
        "author": "Mark Twain",
        "title": "The Adventures of Tom Sawyer",
        "rank": 97,
        "data": {
            "year": 1876,
            "genre": ["Adventure", "Children's Literature"],
            "original_language": "English",
        },
    },
    {
        "author": "Ernest Hemingway",
        "title": "The Sun Also Rises",
        "rank": 98,
        "data": {
            "year": 1926,
            "genre": ["Modernist Novel", "Roman à clef"],
            "original_language": "English",
        },
    },
    {
        "author": "Jack Kerouac",
        "title": "On the Road",
        "rank": 99,
        "data": {
            "year": 1957,
            "genre": ["Beat Generation", "Autobiographical Fiction"],
            "original_language": "English",
        },
    },
    {
        "author": "Fyodor Dostoevsky",
        "title": "The House of the Dead",
        "rank": 100,
        "data": {
            "year": 1862,
            "genre": ["Autobiographical Fiction", "Memoir"],
            "original_language": "Russian",
        },
    },
]

book_titles = [
    "Don Quixote",
    "War and Peace",
    "1984",
    "The Odyssey",
    "Pride and Prejudice",
    "Crime and Punishment",
    "Moby-Dick",
    "One Hundred Years of Solitude",
    "Ulysses",
    "Anna Karenina",
    "Adventures of Huckleberry Finn",
    "The Great Gatsby",
    "In Search of Lost Time",
    "The Lord of the Rings",
    "Hamlet",
    "The Divine Comedy",
    "The Iliad",
    "The Metamorphosis",
    "Great Expectations",
    "Frankenstein",
    "The Stranger",
    "The Catcher in the Rye",
    "Catch-22",
    "Animal Farm",
    "To Kill a Mockingbird",
    "Wuthering Heights",
    "Mrs Dalloway",
    "The Brothers Karamazov",
    "The Old Man and the Sea",
    "Brave New World",
    "The War of the Worlds",
    "The Magic Mountain",
    "Jane Eyre",
    "Gulliver's Travels",
    "The Idiot",
    "Lord of the Flies",
    "Sherlock Holmes: The Complete Novels and Stories",
    "The Grapes of Wrath",
    "The Trial",
    "Madame Bovary",
    "Siddhartha",
    "Twenty Thousand Leagues Under the Sea",
    "Gone with the Wind",
    "Heart of Darkness",
    "The Little Prince",
    "The Picture of Dorian Gray",
    "Billy Budd, Sailor",
    "The Art of War",
    "Slaughterhouse-Five",
    "Dracula",
    "Les Misérables",
    "Middlemarch",
    "The Count of Monte Cristo",
    "The Master and Margarita",
    "Buddenbrooks",
    "Beloved",
    "A Passage to India",
    "The Castle",
    "Midnight's Children",
    "Ficciones",
    "One Flew Over the Cuckoo's Nest",
    "Notes from Underground",
    "Steppenwolf",
    "As I Lay Dying",
    "A Farewell to Arms",
    "Mist",
    "Things Fall Apart",
    "The Unbearable Lightness of Being",
    "The Remains of the Day",
    "Fahrenheit 451",
    "The Hobbit",
    "Lolita",
    "Death of a Salesman",
    "Macbeth",
    "Alice's Adventures in Wonderland",
    "Robinson Crusoe",
    "Of Mice and Men",
    "The Scarlet Letter",
    "Their Eyes Were Watching God",
    "For Whom the Bell Tolls",
    "A Portrait of the Artist as a Young Man",
    "The Bell Jar",
    "Paradise Lost",
    "2001: A Space Odyssey",
    "Treasure Island",
    "The Diary of a Young Girl",
    "Foundation",
    "The Gambler",
    "The Alchemist",
    "Life of Pi",
    "Light in August",
    "The Strange Case of Dr Jekyll and Mr Hyde",
    "Bartleby, the Scrivener",
    "Jude the Obscure",
    "The Name of the Rose",
    "The Hunchback of Notre-Dame",
    "The Adventures of Tom Sawyer",
    "The Sun Also Rises",
    "On the Road",
    "The House of the Dead",
]
